# Actividad 4

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Aperturas_RefL0100N1504_snap_28_aperture_30.dat')

In [6]:
df.head(80)

,GalaxyID,GroupID,SnapNum,Redshift,SubGroupNumber,CentreOfPotential_x,CentreOfPotential_y,CentreOfPotential_z,Stars_Mass,SF_Mass,...,NSF_Hydrogen,NSF_Oxygen,NSF_Metallicity,StarFormationRate,InitialMassWeightedStellarAge,ApertureSize,Mass_Star,SFR_30pkpc,Group_R_Crit200,Group_M_Crit200
0,9498012,28000000000002,28,2.220446e-16,6,8.913222,35.828056,54.839039,1.538708e+11,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,10.139413,30,1.307842e+11,0.000000,1411.312012,3.002119e+14
1,9508202,28000000000002,28,2.220446e-16,7,6.904262,35.705917,57.397373,7.604099e+10,2.281596e+09,...,0.727174,0.004796,0.011342,0.841832,9.455478,30,6.641890e+10,0.823222,1411.312012,3.002119e+14
2,9512113,28000000000002,28,2.220446e-16,8,8.682913,35.504921,54.217369,1.345128e+11,1.514760e+10,...,0.696796,0.010628,0.024796,12.094972,7.656161,30,1.183275e+11,10.984530,1411.312012,3.002119e+14
3,9517736,28000000000002,28,2.220446e-16,9,8.278317,37.063808,54.914932,2.232997e+10,2.754609e+09,...,0.714222,0.007443,0.017283,1.334875,8.117089,30,2.024596e+10,1.322288,1411.312012,3.002119e+14
4,9519365,28000000000002,28,2.220446e-16,10,8.262937,36.454063,55.901993,4.833353e+10,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,8.520104,30,3.944613e+10,0.000000,1411.312012,3.002119e+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,59447030,28000000002588,28,2.220446e-16,1,47.698963,11.869857,11.295007,1.316072e+09,4.785880e+07,...,0.651990,0.019398,0.045520,0.015445,5.233562,30,1.316072e+09,0.015445,162.330292,4.567473e+11
76,10883094,28000000002601,28,2.220446e-16,0,85.621559,98.166000,28.604633,1.490687e+10,2.854157e+08,...,0.741558,0.001995,0.004710,0.186716,8.933957,30,1.469753e+10,0.186716,173.794876,5.605214e+11
77,10883983,28000000002602,28,2.220446e-16,0,21.103628,95.975327,60.586025,9.629412e+09,5.864018e+08,...,0.744326,0.001473,0.003465,0.315015,8.030761,30,9.445810e+09,0.315015,163.174942,4.640002e+11
78,10910419,28000000002638,28,2.220446e-16,0,68.773071,94.707542,24.751190,3.531743e+09,4.724090e+08,...,0.747857,0.000858,0.001921,0.138531,7.675415,30,3.443173e+09,0.138531,145.017624,3.256591e+11
79,3169927,28000000002638,28,2.220446e-16,1,68.777893,94.815109,24.613930,2.592642e+09,3.688181e+08,...,0.731590,0.003986,0.009333,0.128669,6.622097,30,2.574653e+09,0.128669,145.017624,3.256591e+11

In [7]:
df.describe()

,GalaxyID,GroupID,SnapNum,Redshift,SubGroupNumber,CentreOfPotential_x,CentreOfPotential_y,CentreOfPotential_z,Stars_Mass,SF_Mass,...,NSF_Hydrogen,NSF_Oxygen,NSF_Metallicity,StarFormationRate,InitialMassWeightedStellarAge,ApertureSize,Mass_Star,SFR_30pkpc,Group_R_Crit200,Group_M_Crit200
count,1.330000e+04,1.330000e+04,13300.0,1.330000e+04,13300.000000,13300.000000,13300.000000,13300.000000,1.330000e+04,1.330000e+04,...,13300.000000,13300.000000,13300.000000,13300.000000,13300.000000,13300.0,1.330000e+04,13300.000000,13300.000000,1.330000e+04
mean,1.157440e+07,2.800001e+13,28.0,2.220446e-16,14.467143,51.454312,52.331232,48.459022,1.505585e+10,9.513822e+08,...,0.581782,0.003888,0.009638,0.426749,7.477804,30.0,1.210698e+10,0.391699,380.445998,3.146575e+13
std,1.166503e+07,3.486025e+07,0.0,0.000000e+00,49.958821,29.236947,28.430540,26.818288,5.052372e+10,1.833099e+09,...,0.291164,0.006328,0.016502,1.014671,1.422477,0.0,2.509720e+10,0.844074,367.907886,7.932394e+13
min,1.000000e+00,2.800000e+13,28.0,2.220446e-16,0.000000,0.002541,0.004817,0.010571,1.000058e+09,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,2.044023,30.0,8.347781e+08,0.000000,33.527607,4.024593e+09
25%,4.494468e+06,2.800000e+13,28.0,2.220446e-16,0.000000,25.093985,30.234874,26.718544,1.760516e+09,4.810088e+07,...,0.639475,0.000649,0.001489,0.018845,6.490762,30.0,1.737716e+09,0.014294,134.312466,2.587368e+11
50%,1.061103e+07,2.800000e+13,28.0,2.220446e-16,0.000000,54.514576,53.374598,48.402117,3.732724e+09,3.251755e+08,...,0.739389,0.001429,0.003259,0.139267,7.415340,30.0,3.663291e+09,0.134345,209.637512,9.838787e+11
75%,1.283367e+07,2.800000e+13,28.0,2.220446e-16,4.000000,77.456436,77.505547,66.703173,1.144510e+10,1.008747e+09,...,0.745657,0.003372,0.007831,0.428734,8.417295,30.0,1.108336e+10,0.408898,477.557587,1.163013e+13
max,6.593720e+07,2.800090e+13,28.0,2.220446e-16,763.000000,99.997192,99.992584,99.993721,1.905425e+12,5.368436e+10,...,0.751963,0.050391,0.131233,48.093414,12.641494,30.0,4.647067e+11,47.181259,1518.191895,3.736875e+14

In [10]:
df['Stars_Mass']-max(df['Stars_Mass'])

0       -1.751554e+12
1       -1.829384e+12
2       -1.770912e+12
3       -1.883095e+12
4       -1.857092e+12
             ...
13295   -1.903035e+12
13296   -1.904145e+12
13297   -1.903793e+12
13298   -1.902575e+12
13299   -1.904416e+12
Name: Stars_Mass, Length: 13300, dtype: float64

In [16]:
mask = (df['GroupID']==28000000000001)
df_1 = df['Stars_Mass'][mask]
df_1

2553    2.704106e+10
2554    3.856083e+10
2555    4.573218e+10
2556    1.980979e+10
2557    2.073764e+10
            ...
5645    2.798827e+10
5646    3.440095e+10
5647    2.449730e+10
5648    3.793732e+10
5649    2.433223e+10
Name: Stars_Mass, Length: 297, dtype: float64