## Descarga de datos para la actividad 9

In [1]:
# Importar paquetes
import merger_tree_tools as mtt
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
path_lin ='/home/ramiro/Facultad/Tesis/Datos/Actividad 9/' 
# path_win =

[14696151,14875627,16062294,15457919]

In [55]:
# Simulación a usar y datos de galaxia deseada
simu='RefL0100N1504'

snap=28
galid=15457919

In [56]:
# Usuario y contraseña para conectarse a EAGLE DataBase
usr='cht015'
pwd='BH457tfj'

# Descargar todos los IDS necesarios de la galaxia deseada

myIDs=mtt.retrieve_ids(usr,pwd,simu,snap,galid)

# Descargar merger tree completo de la galaxia deseada
# Nombre y alias de la tabla de la cual se quieren descargar datos
table='MorphoKinem'
table_alias='mor'

# Variables que se quiere descargar. OJO!! Asegurarse que estas variables
# estén en la tabla deseada.
columns=[
         'GalaxyID', 'KappaCoRot'
        ]

raw_tree=mtt.download_merger_tree(usr,pwd,simu,myIDs['GalaxyID'],myIDs['LastProgID'],
                                  table=table,table_alias=table_alias,columns=columns)

# NOTA: si ya se tiene descargados en un archivo todas las galaxias de la simu, se puede
#       saltear esta celda, y en su lugar, leer dicho archivo de datos y usar máscaras
#       para seleccionar las galaxias del árbol deseado

# Aplicar condiciones a las galaxias del árbol, si es necesario
mask=(
      (raw_tree['Stars_Mass']>0) &
      (raw_tree['SF_Mass']>0) &
      (raw_tree['SF_Hydrogen']>0) &
      (raw_tree['SF_Oxygen']>0)
     )

In [57]:
# Armar arbol sólo con galaxias seleccionadas según condiciones anteriores
tree={}
for key in raw_tree.keys():
    tree[key]=raw_tree[key]#[mask]
    
print('Number of galaxies in the selected tree: '+str(len(tree['GalaxyID'])))

Number of galaxies in the selected tree: 42

# Ordeno las galaxias según SnapNum creciente
mask_order=(tree['SnapNum']).argsort()
for key in tree.keys():
    tree[key]=tree[key][mask_order]

# Agregar variables al árbol final, si es necesario
tree['sSFR']=tree['StarFormationRate']/tree['Stars_Mass']
tree['SF_logOH']=12+np.log10(tree['SF_Oxygen']/tree['SF_Hydrogen'])-np.log10(16)

In [58]:
tree.keys()

dict_keys(['GalaxyID', 'KappaCoRot', 'SubHaloGalaxyID'])

In [59]:
df = pd.DataFrame(tree)

In [60]:
df

    GalaxyID  KappaCoRot  SubHaloGalaxyID
0   15457919    0.210234         15457919
1   15457920    0.174460         15457920
2   15457921    0.159508         15457921
3   15457922    0.160122         15457922
4   15457923    0.171520         15457923
5   15457924    0.140854         15457924
6   15457925    0.148426         15457925
7   15457926    0.140117         15457926
8   15457927    0.145511         15457927
9   15457928    0.188430         15457928
10  15457929    0.160846         15457929
11  15457930    0.163876         15457930
12  15457931    0.170773         15457931
13  15457932    0.138796         15457932
14  15457933    0.150325         15457933
15  15457934    0.156578         15457934
16  15457935    0.182494         15457935
17  15457936    0.145840         15457936
18  15457937    0.129701         15457937
19  15457938    0.197357         15457938
20  15457939    0.221101         15457939
21  15457940    0.173370         15457940
22  15457941    0.183158         15457941
23  15457942    0.180883         15457942
24  15458242    0.580314         15458242
25  15458243    0.359741         15458243
26  15458244    0.188553         15458244
27  15459159    0.288002         15459159
28  15459160    0.278264         15459160
29  15459161    0.309523         15459161
30  15459672    0.196828         15459672
31  15459673    0.153310         15459673
32  15459674    0.296514         15459674
33  15459675    0.334589         15459675
34  15459676    0.216137         15459676
35  15460897    0.219432         15460897
36  15460898    0.248919         15460898
37  15460899    0.301512         15460899
38  15463860    0.184120         15463860
39  15463861    0.209115         15463861
40  15463862    0.197549         15463862
41  15463863    0.197523         15463863

In [61]:
df.to_csv(path_or_buf= path_lin+'/Actividad_9_Tree('+str(table)+'_'+str(galid)+').dat',index=False)   # Nos guardamos los datos

In [43]:
# Fin

## Catalogos descargados

* Subhalo\
columnas = [
         'GalaxyID','GroupID','LastProgID','TopLeafID','DescendantID',
         'SnapNum','Stars_Mass','SF_Hydrogen','SF_Oxygen','Redshift',
         'StarFormationRate','Stars_Metallicity','SF_Mass','BlackHoleMass','MassType_DM',
         'SF_Metallicity','Vmax'
        ]

* Sizes\
columnas = [
         'GalaxyID','R_halfmass30','R_halfmass100'
        ]

* MorphoKinem\
columnas = [
         'GalaxyID', 'KappaCoRot'
        ]

* FOF\
columnas = ['GroupID','GroupCentreOfPotential_x','GroupCentreOfPotential_y','GroupCentreOfPotential_z'
              ,'Group_M_Crit200','Group_R_Crit200','NumOfSubhalos']