# Script para historias de merger para galaxias mayores a 10^10 en el snap 28

In [1]:
import merger_tree_tools as mtt
import numpy as np
from astropy.table import Table
from astropy.cosmology import Planck15 as cosmo
import h5py
import pandas as pd

In [2]:
path_lin ='/home/ramiro/Datos guardados/Facultad/Tesis/Datos/Proyecto Altas Masas/' 
# path_win =

In [3]:
# Tamaño de visualización de los DataFrame

pd.options.display.max_rows = 28
pd.options.display.max_columns = 50

In [4]:
table  = pd.read_csv(path_lin+'galaxias_NoAGNL0050N0752_stellarmass_between_1e10p6_and_1e10p8_snap_28_full_subhalo.dat')

In [5]:
table

,GroupID,Group_M_Crit200,GalaxyID,Stars_Mass,SF_Mass,SF_Hydrogen,SF_Oxygen,SnapNum,Redshift,StarFormationRate,InitialMassWeightedStellarAge,NSF_Mass,BlackHoleMass,KappaCoRot,RotToDispRatio,DiscToTotal,Ellipticity,Triaxiality,SF_Frac,NSF_Frac,SF_logOH,log_Mbh_Mstar
0,28000000000045,5.907394e+12,2422553,4.873994e+10,1.852153e+10,0.697406,0.011435,28,2.220446e-16,10.205994,6.266541,6.371597e+11,0.0,0.208425,0.212342,0.194095,0.183462,0.397403,0.275366,0.904515,9.010627,-inf
1,28000000000077,2.510587e+12,2794037,4.447796e+10,9.722727e+09,0.668232,0.015339,28,2.220446e-16,4.422296,6.449958,1.223810e+11,0.0,0.591395,1.135398,0.683755,0.696889,0.184061,0.179384,0.693056,9.156743,-inf
2,28000000000089,2.805176e+12,2874743,4.545159e+10,1.153006e+10,0.684775,0.013114,28,2.220446e-16,3.981623,7.014984,1.795804e+11,0.0,0.691320,1.498982,0.818271,0.754477,0.093119,0.202347,0.759126,9.078067,-inf
3,28000000000095,2.321445e+12,2909752,6.707772e+10,8.648298e+09,0.649125,0.018550,28,2.220446e-16,4.533889,7.031512,2.231222e+11,0.0,0.502670,0.845335,0.559191,0.613273,0.032173,0.114205,0.746607,9.251895,-inf
4,28000000000096,1.987126e+12,2916107,5.484394e+10,1.090185e+10,0.655055,0.018072,28,2.220446e-16,6.671921,5.766932,2.564885e+11,0.0,0.459209,1.018006,0.703411,0.342343,0.080638,0.165818,0.795969,9.236603,-inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,28000000000187,1.131913e+12,3315360,4.332117e+10,6.031738e+09,0.673298,0.014482,28,2.220446e-16,2.857086,7.291619,5.408375e+10,0.0,0.461776,0.555696,0.353790,0.633431,0.060261,0.122216,0.522868,9.128487,-inf
52,28000000000193,9.888729e+11,3333632,3.629812e+10,5.262310e+09,0.656315,0.017134,28,2.220446e-16,5.111354,6.138680,6.413114e+10,0.0,0.622976,1.298394,0.758969,0.696382,0.408387,0.126618,0.606776,9.212630,-inf
53,28000000000225,8.900814e+11,3421831,4.561196e+10,4.227182e+09,0.640801,0.019638,28,2.220446e-16,2.142556,7.303512,2.920086e+10,0.0,0.493938,0.885269,0.616265,0.624974,0.463247,0.084817,0.369444,9.282255,-inf
54,28000000000230,8.613537e+11,3434066,4.331474e+10,3.744926e+09,0.669367,0.015303,28,2.220446e-16,1.425690,8.379180,3.491466e+10,0.0,0.538929,1.061099,0.720014,0.701341,0.058200,0.079578,0.425922,9.154995,-inf
55,28000000000244,7.819284e+11,3466406,3.653870e+10,2.701625e+09,0.589001,0.028468,28,2.220446e-16,1.845834,5.681083,2.983556e+10,0.0,0.526204,1.042809,0.707203,0.608486,0.233098,0.068848,0.431924,9.480124,-inf

In [6]:
table['log(SF_Mass)']   = np.log10(table['SF_Mass'])
table['log(Stars_Mass)']= np.log10(table['Stars_Mass'])
table

,GroupID,Group_M_Crit200,GalaxyID,Stars_Mass,SF_Mass,SF_Hydrogen,SF_Oxygen,SnapNum,Redshift,StarFormationRate,InitialMassWeightedStellarAge,NSF_Mass,BlackHoleMass,KappaCoRot,RotToDispRatio,DiscToTotal,Ellipticity,Triaxiality,SF_Frac,NSF_Frac,SF_logOH,log_Mbh_Mstar,log(SF_Mass),log(Stars_Mass)
0,28000000000045,5.907394e+12,2422553,4.873994e+10,1.852153e+10,0.697406,0.011435,28,2.220446e-16,10.205994,6.266541,6.371597e+11,0.0,0.208425,0.212342,0.194095,0.183462,0.397403,0.275366,0.904515,9.010627,-inf,10.267677,10.687885
1,28000000000077,2.510587e+12,2794037,4.447796e+10,9.722727e+09,0.668232,0.015339,28,2.220446e-16,4.422296,6.449958,1.223810e+11,0.0,0.591395,1.135398,0.683755,0.696889,0.184061,0.179384,0.693056,9.156743,-inf,9.987788,10.648145
2,28000000000089,2.805176e+12,2874743,4.545159e+10,1.153006e+10,0.684775,0.013114,28,2.220446e-16,3.981623,7.014984,1.795804e+11,0.0,0.691320,1.498982,0.818271,0.754477,0.093119,0.202347,0.759126,9.078067,-inf,10.061832,10.657549
3,28000000000095,2.321445e+12,2909752,6.707772e+10,8.648298e+09,0.649125,0.018550,28,2.220446e-16,4.533889,7.031512,2.231222e+11,0.0,0.502670,0.845335,0.559191,0.613273,0.032173,0.114205,0.746607,9.251895,-inf,9.936931,10.826578
4,28000000000096,1.987126e+12,2916107,5.484394e+10,1.090185e+10,0.655055,0.018072,28,2.220446e-16,6.671921,5.766932,2.564885e+11,0.0,0.459209,1.018006,0.703411,0.342343,0.080638,0.165818,0.795969,9.236603,-inf,10.037500,10.739129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,28000000000187,1.131913e+12,3315360,4.332117e+10,6.031738e+09,0.673298,0.014482,28,2.220446e-16,2.857086,7.291619,5.408375e+10,0.0,0.461776,0.555696,0.353790,0.633431,0.060261,0.122216,0.522868,9.128487,-inf,9.780442,10.636700
52,28000000000193,9.888729e+11,3333632,3.629812e+10,5.262310e+09,0.656315,0.017134,28,2.220446e-16,5.111354,6.138680,6.413114e+10,0.0,0.622976,1.298394,0.758969,0.696382,0.408387,0.126618,0.606776,9.212630,-inf,9.721176,10.559884
53,28000000000225,8.900814e+11,3421831,4.561196e+10,4.227182e+09,0.640801,0.019638,28,2.220446e-16,2.142556,7.303512,2.920086e+10,0.0,0.493938,0.885269,0.616265,0.624974,0.463247,0.084817,0.369444,9.282255,-inf,9.626051,10.659079
54,28000000000230,8.613537e+11,3434066,4.331474e+10,3.744926e+09,0.669367,0.015303,28,2.220446e-16,1.425690,8.379180,3.491466e+10,0.0,0.538929,1.061099,0.720014,0.701341,0.058200,0.079578,0.425922,9.154995,-inf,9.573443,10.636636
55,28000000000244,7.819284e+11,3466406,3.653870e+10,2.701625e+09,0.589001,0.028468,28,2.220446e-16,1.845834,5.681083,2.983556e+10,0.0,0.526204,1.042809,0.707203,0.608486,0.233098,0.068848,0.431924,9.480124,-inf,9.431625,10.562753

In [7]:
table_a = table[
                (table['log(Stars_Mass)']>=10)
               ].copy()
table_a

,GroupID,Group_M_Crit200,GalaxyID,Stars_Mass,SF_Mass,SF_Hydrogen,SF_Oxygen,SnapNum,Redshift,StarFormationRate,InitialMassWeightedStellarAge,NSF_Mass,BlackHoleMass,KappaCoRot,RotToDispRatio,DiscToTotal,Ellipticity,Triaxiality,SF_Frac,NSF_Frac,SF_logOH,log_Mbh_Mstar,log(SF_Mass),log(Stars_Mass)
0,28000000000045,5.907394e+12,2422553,4.873994e+10,1.852153e+10,0.697406,0.011435,28,2.220446e-16,10.205994,6.266541,6.371597e+11,0.0,0.208425,0.212342,0.194095,0.183462,0.397403,0.275366,0.904515,9.010627,-inf,10.267677,10.687885
1,28000000000077,2.510587e+12,2794037,4.447796e+10,9.722727e+09,0.668232,0.015339,28,2.220446e-16,4.422296,6.449958,1.223810e+11,0.0,0.591395,1.135398,0.683755,0.696889,0.184061,0.179384,0.693056,9.156743,-inf,9.987788,10.648145
2,28000000000089,2.805176e+12,2874743,4.545159e+10,1.153006e+10,0.684775,0.013114,28,2.220446e-16,3.981623,7.014984,1.795804e+11,0.0,0.691320,1.498982,0.818271,0.754477,0.093119,0.202347,0.759126,9.078067,-inf,10.061832,10.657549
3,28000000000095,2.321445e+12,2909752,6.707772e+10,8.648298e+09,0.649125,0.018550,28,2.220446e-16,4.533889,7.031512,2.231222e+11,0.0,0.502670,0.845335,0.559191,0.613273,0.032173,0.114205,0.746607,9.251895,-inf,9.936931,10.826578
4,28000000000096,1.987126e+12,2916107,5.484394e+10,1.090185e+10,0.655055,0.018072,28,2.220446e-16,6.671921,5.766932,2.564885e+11,0.0,0.459209,1.018006,0.703411,0.342343,0.080638,0.165818,0.795969,9.236603,-inf,10.037500,10.739129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,28000000000187,1.131913e+12,3315360,4.332117e+10,6.031738e+09,0.673298,0.014482,28,2.220446e-16,2.857086,7.291619,5.408375e+10,0.0,0.461776,0.555696,0.353790,0.633431,0.060261,0.122216,0.522868,9.128487,-inf,9.780442,10.636700
52,28000000000193,9.888729e+11,3333632,3.629812e+10,5.262310e+09,0.656315,0.017134,28,2.220446e-16,5.111354,6.138680,6.413114e+10,0.0,0.622976,1.298394,0.758969,0.696382,0.408387,0.126618,0.606776,9.212630,-inf,9.721176,10.559884
53,28000000000225,8.900814e+11,3421831,4.561196e+10,4.227182e+09,0.640801,0.019638,28,2.220446e-16,2.142556,7.303512,2.920086e+10,0.0,0.493938,0.885269,0.616265,0.624974,0.463247,0.084817,0.369444,9.282255,-inf,9.626051,10.659079
54,28000000000230,8.613537e+11,3434066,4.331474e+10,3.744926e+09,0.669367,0.015303,28,2.220446e-16,1.425690,8.379180,3.491466e+10,0.0,0.538929,1.061099,0.720014,0.701341,0.058200,0.079578,0.425922,9.154995,-inf,9.573443,10.636636
55,28000000000244,7.819284e+11,3466406,3.653870e+10,2.701625e+09,0.589001,0.028468,28,2.220446e-16,1.845834,5.681083,2.983556e+10,0.0,0.526204,1.042809,0.707203,0.608486,0.233098,0.068848,0.431924,9.480124,-inf,9.431625,10.562753

In [8]:
data = {'GalaxyID_test':[],'GroupID_test':[],
        'Lm_snap1':[],'Lm_snap2':[],'Lm_snap3':[],'Lm_snap4':[],
        'Lm_snap5':[],'Lm_snap6':[],'Lm_snap7':[],'Lm_snap8':[],
        'Lm_snap9':[],'Lm_snap10':[],'Lm_snap11':[],'Lm_snap12':[],
        'Lm_snap13':[],'Lm_snap14':[],'Lm_snap15':[],'Lm_snap16':[],
        'Lm_snap17':[],'Lm_snap18':[],'Lm_snap19':[],'Lm_snap20':[],
        'Lm_snap21':[],'Lm_snap22':[],'Lm_snap23':[],'Lm_snap24':[],
        'Lm_snap25':[],'Lm_snap26':[],'Lm_snap27':[],'Lm_snap28':[]}

DATA_merge = pd.DataFrame(data=data)

In [9]:
simu='NoAGNL0050N0752'
snap=28

In [10]:
long = len(table_a['GalaxyID'])

# long = 10

# Usuario y contraseña para conectarse a EAGLE DataBase
usr='cht015'
pwd='BH457tfj'

# Descargar merger tree completo de la galaxia deseada
# Nombre y alias de la tabla de la cual se quieren descargar datos
table='SubHalo'
table_alias='sub'

# Variables que se quiere descargar. OJO!! Asegurarse que estas variables
# estén en la tabla deseada.
columns=[
          'GalaxyID','LastProgID','TopLeafID','DescendantID',
          'SnapNum','Redshift','Stars_Mass','SF_Mass','GroupID'
        ]

#Loop para todas las galaxias de la tabla
for p in np.arange(long):

    galid = table_a['GalaxyID'].to_numpy()[p]
 
    # Descargar todos los IDS necesarios de la galaxia deseada

    myIDs    = mtt.retrieve_ids(usr,pwd,simu,snap,galid)

    raw_tree = mtt.download_merger_tree(usr,pwd,simu,myIDs['GalaxyID'],myIDs['LastProgID'],
                                  table=table,table_alias=table_alias,columns=columns)
    
    # Aplicar condiciones a las galaxias del árbol, si es necesario
    mask = (
            (raw_tree['Stars_Mass']>0)
           )

    # Armar arbol sólo con galaxias seleccionadas según condiciones anteriores
    tree = {}
    for key in raw_tree.keys():
        tree[key]=raw_tree[key][mask]
        
    # Ordeno las galaxias según SnapNum creciente
    mask_order = (tree['SnapNum']).argsort()
    for key in tree.keys():
        tree[key] = tree[key][mask_order]

    # Armo un diccionario con solo la main branch del árbol
    main_branch = {}
    # Select galaxies in the main branch 
    mask_main = np.logical_and(tree['GalaxyID']>=myIDs['GalaxyID'],
                               tree['GalaxyID']<=myIDs['TopLeafID']) 

    for key in tree.keys():
        main_branch[key] = tree[key][mask_main]

        
    xplot_main = main_branch['SnapNum']
    
    # Calculo level of merger
    level_merger=[1]       # Inicializo con un 1, porque la primer galaxia del main branch 
                           # no viene de ninguna fusión...
    
    for k in range(np.size(xplot_main)-1):
        m1=main_branch['Stars_Mass'][k]+main_branch['SF_Mass'][k]
        mask=(tree['DescendantID']==main_branch['GalaxyID'][k+1]) & (tree['SnapNum']!=28) 
        # La condición de snapnum distinto a 28 es porque galaxias a z=0 no tienen descendiente,
        # y se les asigna como DescendantID su propio GalaxyID
        m2=np.sum(tree['Stars_Mass'][mask])+np.sum(tree['SF_Mass'][mask])
        level=m2/m1
        level_merger=np.append(level_merger,level)  
        
    #Calculamos las variables que nos interesan:
    
    i=0 

    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==1)):
        Lm_1 = level_merger[i]
        i=i+1
    else: Lm_1 = np.nan
    
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==2)):
        Lm_2 = level_merger[i]
        i=i+1
    else: Lm_2 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==3)):
        Lm_3 = level_merger[i]
        i=i+1
    else: Lm_3 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==4)):
        Lm_4 = level_merger[i]
        i=i+1
    else: Lm_4 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==5)):
        Lm_5 = level_merger[i]
        i=i+1
    else: Lm_5 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==6)):
        Lm_6 = level_merger[i]
        i=i+1
    else: Lm_6 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==7)):
        Lm_7 = level_merger[i]
        i=i+1
    else: Lm_7 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==8)):
        Lm_8 = level_merger[i]
        i=i+1
    else: Lm_8 = np.nan
    
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==9)):
        Lm_9 = level_merger[i]
        i=i+1
    else: Lm_9 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==10)):
        Lm_10 = level_merger[i]
        i=i+1
    else: Lm_10 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==11)):
        Lm_11 = level_merger[i]
        i=i+1
    else: Lm_11 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==12)):
        Lm_12 = level_merger[i]
        i=i+1
    else: Lm_12 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==13)):
        Lm_13 = level_merger[i]
        i=i+1
    else: Lm_13 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==14)):
        Lm_14 = level_merger[i]
        i=i+1
    else: Lm_14 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==15)):
        Lm_15 = level_merger[i]
        i=i+1
    else: Lm_15 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==16)):
        Lm_16 = level_merger[i]
        i=i+1
    else: Lm_16 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==17)):
        Lm_17 = level_merger[i]
        i=i+1
    else: Lm_17 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==18)):
        Lm_18 = level_merger[i]
        i=i+1
    else: Lm_18 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==19)):
        Lm_19 = level_merger[i]
        i=i+1
    else: Lm_19 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==20)):
        Lm_20 = level_merger[i]
        i=i+1
    else: Lm_20 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==21)):
        Lm_21 = level_merger[i]
        i=i+1
    else: Lm_21 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==22)):
        Lm_22 = level_merger[i]
        i=i+1
    else: Lm_22 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==23)):
        Lm_23 = level_merger[i]
        i=i+1
    else: Lm_23 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==24)):
        Lm_24 = level_merger[i]
        i=i+1
    else: Lm_24 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==25)):
        Lm_25 = level_merger[i]
        i=i+1
    else: Lm_25 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==26)):
        Lm_26 = level_merger[i]
        i=i+1
    else: Lm_26 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==27)):
        Lm_27 = level_merger[i]
        i=i+1
    else: Lm_27 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==28)):
        Lm_28 = level_merger[i]
        i=i+1
    else: Lm_28 = np.nan
   
    
    
    


    data = {'GalaxyID_test':table_a['GalaxyID'].to_numpy()[p],'GroupID_test':table_a['GroupID'].to_numpy()[p],
            'Lm_snap1':Lm_1,'Lm_snap2':Lm_2,'Lm_snap3':Lm_3,'Lm_snap4':Lm_4,
            'Lm_snap5':Lm_5,'Lm_snap6':Lm_6,'Lm_snap7':Lm_7,'Lm_snap8':Lm_8,
            'Lm_snap9':Lm_9,'Lm_snap10':Lm_10,'Lm_snap11':Lm_11,'Lm_snap12':Lm_12,
            'Lm_snap13':Lm_13,'Lm_snap14':Lm_14,'Lm_snap15':Lm_15,'Lm_snap16':Lm_16,
            'Lm_snap17':Lm_17,'Lm_snap18':Lm_18,'Lm_snap19':Lm_19,'Lm_snap20':Lm_20,
            'Lm_snap21':Lm_21,'Lm_snap22':Lm_22,'Lm_snap23':Lm_23,'Lm_snap24':Lm_24,
            'Lm_snap25':Lm_25,'Lm_snap26':Lm_26,'Lm_snap27':Lm_27,'Lm_snap28':Lm_28}

    DATA_merge = DATA_merge.append(data,ignore_index=True)
    
    print('Porcentaje:',round(float((p+1)/long),2),end='\r')

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

In [11]:
DATA_merge = DATA_merge.astype({'GalaxyID_test':int,'GroupID_test':int,
                                'Lm_snap1':float, 'Lm_snap2':float, 'Lm_snap3':float, 'Lm_snap4':float,
                                'Lm_snap5':float, 'Lm_snap6':float, 'Lm_snap7':float, 'Lm_snap8':float,
                                'Lm_snap9':float, 'Lm_snap10':float,'Lm_snap11':float,'Lm_snap12':float,
                                'Lm_snap13':float,'Lm_snap14':float,'Lm_snap15':float,'Lm_snap16':float,
                                'Lm_snap17':float,'Lm_snap18':float,'Lm_snap19':float,'Lm_snap20':float,
                                'Lm_snap21':float,'Lm_snap22':float,'Lm_snap23':float,'Lm_snap24':float,
                                'Lm_snap25':float,'Lm_snap26':float,'Lm_snap27':float,'Lm_snap28':float})

In [12]:
DATA_merge

,GalaxyID_test,GroupID_test,Lm_snap1,Lm_snap2,Lm_snap3,Lm_snap4,Lm_snap5,Lm_snap6,Lm_snap7,Lm_snap8,Lm_snap9,Lm_snap10,Lm_snap11,Lm_snap12,Lm_snap13,Lm_snap14,Lm_snap15,Lm_snap16,Lm_snap17,Lm_snap18,Lm_snap19,Lm_snap20,Lm_snap21,Lm_snap22,Lm_snap23,Lm_snap24,Lm_snap25,Lm_snap26,Lm_snap27,Lm_snap28
0,2422553,28000000000045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,153.395920,1.027606,1.000000,15.033673,1.150702,1.123952
1,2794037,28000000000077,NaN,1.0,1.0,1.000000,1.141045,1.000000,1.000000,1.000000,1.000000,1.000000,1.291500,1.130867,1.027379,1.004284,1.001929,1.078370,1.060465,1.001958,1.396046,1.005928,1.064743,1.000027,1.011130,1.002825,1.000144,1.000000,1.000045,1.003087
2,2874743,28000000000089,NaN,1.0,1.0,1.000000,1.000000,1.020554,1.000000,1.049220,1.015175,1.461086,1.016436,1.005843,1.012017,1.044937,1.000910,1.002344,1.032843,1.020746,1.020869,1.047031,1.033631,1.035837,1.011820,1.027238,1.035833,1.033938,1.024504,1.029082
3,2909752,28000000000095,NaN,NaN,1.0,1.134469,1.000000,1.027000,1.010348,1.166992,1.000000,1.093654,1.000000,1.003629,1.370386,1.007201,1.136142,1.000924,1.011405,1.014178,1.022613,1.444742,1.016895,1.012665,1.001377,1.002495,1.025546,1.000062,1.000015,1.001780
4,2916107,28000000000096,NaN,NaN,1.0,2.265458,1.000000,1.000000,1.000000,1.000000,1.028105,1.000000,1.009491,1.012380,1.220577,1.000000,1.008914,1.002928,1.239389,1.007780,1.077727,1.044760,1.045833,1.020605,1.020927,1.013415,1.023750,1.015586,1.002842,1.323763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,3315360,28000000000187,NaN,NaN,NaN,NaN,1.000000,1.043361,1.000000,1.000000,1.023095,1.004088,1.223981,1.004166,1.011469,1.002048,1.000000,1.035604,1.016533,1.006515,1.069634,1.000148,1.003545,1.000160,1.038024,1.005880,1.000000,1.002134,1.000000,1.001991
52,3333632,28000000000193,NaN,NaN,1.0,5.095816,1.065282,1.000000,1.000000,1.008364,1.013828,1.004306,1.000000,1.007369,1.447163,1.001745,1.000000,1.018839,1.000958,1.000104,1.032601,1.027498,1.000136,1.000000,1.004195,1.000068,1.004729,1.000060,1.000000,1.000938
53,3421831,28000000000225,NaN,NaN,NaN,1.000000,1.000000,1.146278,1.036119,1.000000,1.059989,1.035235,1.120506,1.018946,1.031421,1.020391,1.032650,1.147804,1.065748,1.014035,1.013312,1.007095,1.002940,1.000032,1.000000,1.000000,1.000000,1.161767,1.000000,1.000000
54,3434066,28000000000230,NaN,1.0,1.0,1.000000,2.628286,1.008435,1.101922,1.001453,1.001437,1.005285,1.003487,1.000000,1.001627,1.000294,1.019341,1.000000,1.012679,1.000305,1.000292,1.011676,1.017289,1.003540,1.030852,1.017014,1.034362,1.034623,1.035313,1.024727
55,3466406,28000000000244,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.485565,1.000000,1.645220,1.000000,1.158157,1.066742,1.000000,1.003230,1.000788,1.000614,1.001363,1.001163,1.112413,1.068572,1.352761,1.007027,1.000097,1.000000,1.000000,1.000000,1.000000

In [13]:
DATA_merge.to_csv(path_or_buf= path_lin+'/Merger_history_altas_masas_mayores_a_10_NoAGNL0050N0752_snap_28.dat',index=False) # Nos guardamos los datos

In [14]:
table_a.to_csv(path_or_buf= path_lin+'/bin_proyecto_altas_masas_mayores_a_10_NoAGNL0050N0752_snap_28.dat',index=False)

* Snapshot 19 = Redshift 1
* Snapshot 28 = Redshift 0

## Pruebas fraction of merger

In [3]:
DATA_merge  = pd.read_csv(path_lin+'/Actividad_8(merger_history_tesis).dat')

In [20]:
mask = (DATA_merge['Lm_snap6'] == 0)
DATA_merge[mask]

,GalaxyID_test,GroupID_test,Lm_snap1,Lm_snap2,Lm_snap3,Lm_snap4,Lm_snap5,Lm_snap6,Lm_snap7,Lm_snap8,...,Lm_snap19,Lm_snap20,Lm_snap21,Lm_snap22,Lm_snap23,Lm_snap24,Lm_snap25,Lm_snap26,Lm_snap27,Lm_snap28
7,2727611,28000000000002,NaN,NaN,1.0,NaN,NaN,0.0,1.891800,1.000000,...,1.018315,1.033089,1.068498,1.000000,NaN,NaN,NaN,0.00000,NaN,NaN
14,4470669,28000000000004,NaN,NaN,1.0,1.0,NaN,0.0,1.000000,1.000000,...,1.023634,1.000000,1.027689,1.029271,1.015195,1.006829,1.000000,1.00000,1.000000,NaN
18,10507082,28000000002364,NaN,NaN,1.0,NaN,NaN,0.0,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
24,10352660,28000000002189,NaN,NaN,1.0,1.0,NaN,0.0,1.000000,1.000000,...,1.000000,1.474600,1.333145,1.000000,1.000000,1.007035,1.000000,1.00000,1.000000,1.000000
34,21793,28000000000000,NaN,1.0,NaN,NaN,NaN,0.0,2.658798,1.000000,...,1.043703,1.000000,1.004681,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,8667711,28000000000817,NaN,1.0,NaN,NaN,NaN,0.0,1.000000,1.000000,...,1.047138,1.029600,1.006176,1.000000,1.037501,1.012499,1.000626,1.00000,1.000000,1.000000
3602,18385552,28000000001003,NaN,1.0,NaN,NaN,NaN,0.0,1.000000,1.000000,...,1.000000,1.010950,1.016656,1.026810,1.010499,1.007426,1.011448,1.00701,1.009407,1.017955
3614,2979098,28000000001336,NaN,NaN,NaN,1.0,NaN,0.0,1.000000,1.000000,...,1.000000,1.000000,1.006409,1.000000,1.000000,1.023178,1.007344,1.00000,1.033620,1.016327
3622,9733375,28000000001609,NaN,NaN,1.0,NaN,NaN,0.0,1.000000,1.000000,...,1.042202,1.000000,1.000000,1.000000,1.000000,1.003019,1.000000,1.00000,1.000000,1.022765
3623,9861180,28000000001714,NaN,NaN,1.0,NaN,NaN,0.0,1.250106,1.190671,...,1.019086,1.000000,1.000000,1.000000,1.005158,1.000000,1.000000,1.00000,1.000000,1.000000

In [ ]:
# Fin