In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go

In [30]:
table  = pd.read_csv('Aperturas_RefL0100N1504_snap_28_aperture_30.dat',index_col='GalaxyID')
table_a= table
table_a

,GroupID,SnapNum,Redshift,SubGroupNumber,CentreOfPotential_x,CentreOfPotential_y,CentreOfPotential_z,Stars_Mass,SF_Mass,NSF_Mass,...,NSF_Hydrogen,NSF_Oxygen,NSF_Metallicity,StarFormationRate,InitialMassWeightedStellarAge,ApertureSize,Mass_Star,SFR_30pkpc,Group_R_Crit200,Group_M_Crit200
GalaxyID,,,,,,,,,,,,,,,,,,,,,
9498012,28000000000002,28,2.220446e-16,6,8.913222,35.828056,54.839039,1.538708e+11,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,10.139413,30,1.307842e+11,0.000000,1411.312012,3.002119e+14
9508202,28000000000002,28,2.220446e-16,7,6.904262,35.705917,57.397373,7.604099e+10,2.281596e+09,2.092023e+09,...,0.727174,0.004796,0.011342,0.841832,9.455478,30,6.641890e+10,0.823222,1411.312012,3.002119e+14
9512113,28000000000002,28,2.220446e-16,8,8.682913,35.504921,54.217369,1.345128e+11,1.514760e+10,1.042460e+09,...,0.696796,0.010628,0.024796,12.094972,7.656161,30,1.183275e+11,10.984530,1411.312012,3.002119e+14
9517736,28000000000002,28,2.220446e-16,9,8.278317,37.063808,54.914932,2.232997e+10,2.754609e+09,2.897005e+09,...,0.714222,0.007443,0.017283,1.334875,8.117089,30,2.024596e+10,1.322288,1411.312012,3.002119e+14
9519365,28000000000002,28,2.220446e-16,10,8.262937,36.454063,55.901993,4.833353e+10,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,8.520104,30,3.944613e+10,0.000000,1411.312012,3.002119e+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4317555,28000100003223,28,2.220446e-16,0,17.477247,79.643379,54.909241,2.390242e+09,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,8.292501,30,2.374284e+09,0.000000,89.337975,7.614508e+10
4710749,28000100004466,28,2.220446e-16,0,58.681110,84.345787,24.601583,1.280501e+09,3.723092e+08,1.467157e+09,...,0.738459,0.002793,0.006326,0.140465,6.375748,30,1.277753e+09,0.140465,92.395576,8.424494e+10
5387790,28000200000262,28,2.220446e-16,0,70.492355,5.389233,91.000664,1.631883e+09,4.478066e+08,2.899414e+09,...,0.734583,0.003821,0.008329,0.148282,5.915991,30,1.589539e+09,0.148282,76.062782,4.699878e+10
6104686,28000200004222,28,2.220446e-16,0,12.975779,81.673553,52.292992,2.849959e+09,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,9.001393,30,2.772405e+09,0.000000,71.829155,3.958096e+10
61518775,28000900002358,28,2.220446e-16,0,8.211574,76.852783,48.471100,1.009073e+09,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,10.406497,30,1.002521e+09,0.000000,39.541702,6.601791e+09

In [31]:
G_test = max(table['Stars_Mass'])
mask = (table['Stars_Mass']==G_test)
xmax = table_a['CentreOfPotential_x'][mask]
ymax = table_a['CentreOfPotential_y'][mask]
zmax = table_a['CentreOfPotential_z'][mask]

In [32]:
table_a['Distancias_test'] = np.sqrt((table_a['CentreOfPotential_x']-list(xmax))**2+(table_a['CentreOfPotential_y']-list(ymax))**2+(table_a['CentreOfPotential_z']-list(zmax))**2)

In [33]:
table_a

,GroupID,SnapNum,Redshift,SubGroupNumber,CentreOfPotential_x,CentreOfPotential_y,CentreOfPotential_z,Stars_Mass,SF_Mass,NSF_Mass,...,NSF_Oxygen,NSF_Metallicity,StarFormationRate,InitialMassWeightedStellarAge,ApertureSize,Mass_Star,SFR_30pkpc,Group_R_Crit200,Group_M_Crit200,Distancias_test
GalaxyID,,,,,,,,,,,,,,,,,,,,,
9498012,28000000000002,28,2.220446e-16,6,8.913222,35.828056,54.839039,1.538708e+11,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,10.139413,30,1.307842e+11,0.000000,1411.312012,3.002119e+14,40.608630
9508202,28000000000002,28,2.220446e-16,7,6.904262,35.705917,57.397373,7.604099e+10,2.281596e+09,2.092023e+09,...,0.004796,0.011342,0.841832,9.455478,30,6.641890e+10,0.823222,1411.312012,3.002119e+14,41.131243
9512113,28000000000002,28,2.220446e-16,8,8.682913,35.504921,54.217369,1.345128e+11,1.514760e+10,1.042460e+09,...,0.010628,0.024796,12.094972,7.656161,30,1.183275e+11,10.984530,1411.312012,3.002119e+14,40.805774
9517736,28000000000002,28,2.220446e-16,9,8.278317,37.063808,54.914932,2.232997e+10,2.754609e+09,2.897005e+09,...,0.007443,0.017283,1.334875,8.117089,30,2.024596e+10,1.322288,1411.312012,3.002119e+14,39.361073
9519365,28000000000002,28,2.220446e-16,10,8.262937,36.454063,55.901993,4.833353e+10,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,8.520104,30,3.944613e+10,0.000000,1411.312012,3.002119e+14,40.145207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4317555,28000100003223,28,2.220446e-16,0,17.477247,79.643379,54.909241,2.390242e+09,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,8.292501,30,2.374284e+09,0.000000,89.337975,7.614508e+10,14.410468
4710749,28000100004466,28,2.220446e-16,0,58.681110,84.345787,24.601583,1.280501e+09,3.723092e+08,1.467157e+09,...,0.002793,0.006326,0.140465,6.375748,30,1.277753e+09,0.140465,92.395576,8.424494e+10,58.619057
5387790,28000200000262,28,2.220446e-16,0,70.492355,5.389233,91.000664,1.631883e+09,4.478066e+08,2.899414e+09,...,0.003821,0.008329,0.148282,5.915991,30,1.589539e+09,0.148282,76.062782,4.699878e+10,104.981051
6104686,28000200004222,28,2.220446e-16,0,12.975779,81.673553,52.292992,2.849959e+09,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,9.001393,30,2.772405e+09,0.000000,71.829155,3.958096e+10,10.519927
61518775,28000900002358,28,2.220446e-16,0,8.211574,76.852783,48.471100,1.009073e+09,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,10.406497,30,1.002521e+09,0.000000,39.541702,6.601791e+09,2.962880

In [28]:
xmax

GalaxyID
21379521    5.563246
Name: CentreOfPotential_x, dtype: float64

In [20]:
(6.904262-5.563546250122588)**2

1.7975187219693514